// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SagaStateMachineWorker.Models;

namespace SagaStateMachineWorker.Migrations
{
    [DbContext(typeof(OrderStateDbContext))]
    [Migration("20220204122753_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SagaStateMachineWorker.Models.OrderStateInstance", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("CorrelationId");

                    b.ToTable("OrderStateInstance");
                });

            modelBuilder.Entity("SagaStateMachineWorker.Models.OrderStateInstance", b =>
                {
                    b.OwnsOne("SagaStateMachineWorker.Models.PaymentOwnedInstance", "Payment", b1 =>
                        {
                            b1.Property<Guid>("OrderStateInstanceCorrelationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CVV")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CardName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CardNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Expiration")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("TotalPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("OrderStateInstanceCorrelationId");

                            b1.ToTable("OrderStateInstance");

                            b1.WithOwner()
                                .HasForeignKey("OrderStateInstanceCorrelationId");
                        });

                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
